# Generated by Django 5.0 on 2023-12-08 18:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_user'),
        ('movies_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_orders',
            field=models.ManyToManyField(related_name='ordered_movies', through='movies_orders.MovieOrder', to=settings.AUTH_USER_MODEL),
        ),
    ]
